[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 5
maxMessageSize = 200

[browser]
gatherUsageStats = false

[runner]
fastReruns = true 
